---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.27"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  features:
  - Added multi-configuration support - create multiple named poster configurations with different styles
  - Added series assignment system - assign specific series to use custom poster configurations
  - Added default configuration that applies to all unassigned series
  - Added visual series tags with poster thumbnails in configuration UI
  - Added rename functionality for poster configurations
  fixes: 
  - Fixed XML serialization error preventing plugin from loading (ICollection to List conversion)
  - Fixed series names displaying as "series.Name" instead of actual names in UI
  technical:
  - Refactored PosterConfiguration to use List<Guid> with proper XML serialization support
  - Added Name property to PosterConfiguration for user-friendly identification
  - Updated UI to use DOM manipulation instead of innerHTML to prevent translation system conflicts
  - Added SuppressMessage attributes for CA1002 and CA2227 code analysis warnings
  other:
  - Improved UI styling with Jellyfin-themed series cards including poster images and hover effects
  - Added delete protection for default configuration
  - Improved configuration dropdown to display "Default" for first configuration
  documentation:
  - Updated configuration page with better field descriptions for multi-configuration workflow