---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.11.13"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using intelligent multi-quality frame analysis, blur detection, and professional-grade rendering. Features advanced brightness and sharpness scoring to avoid dark scenes and motion blur, combined with studio-quality text rendering and image processing.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  improvements:
  - Added 60-second timeout per FFmpeg frame extraction to prevent hung processes
  - Added FFmpeg process kill on task cancellation and timeout to prevent zombie processes
  - Added database initialization guard that blocks callers until DB is ready
  - Added database wait gate to scheduled task and reset history endpoint
  fixes:
  - Fixed temp file accumulation from unhandled exceptions during frame quality analysis
  - Fixed database NullReferenceException when methods called before initialization completes
  - Fixed custom font cache permanently caching missing files instead of retrying
