---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "1.0.0.0"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "General"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog: >
  🎉 Initial Release v1.0.0.0

  ✨ Features:
  • Three distinct poster styles: Standard, Cutout, and Numeral
  • Smart frame extraction with black scene detection
  • Fully customizable typography and colors
  • Multiple aspect ratio support (16:9, 3:2, 4:3, custom)
  • Automatic episode numbering with Roman numerals
  • Text-to-speech number conversion for cutout style
  • Configurable overlay effects and background colors
  • Episode title display with intelligent text wrapping
  • Safe area positioning and automatic font scaling

  🛠️ Technical:
  • Built for Jellyfin 10.10.7+ with .NET 8.0
  • FFmpeg integration for video frame analysis
  • SkiaSharp graphics rendering engine
  • Comprehensive configuration options via web UI
  • Support for all FFmpeg-compatible video formats

  📋 Poster Styles:
  • Standard: Classic overlay with episode info and titles
  • Cutout: Large transparent episode numbers revealing background
  • Numeral: Elegant Roman numeral display with custom styling

  🎨 Customization:
  • Font family selection from extensive library
  • Font styles: Normal, Bold, Italic, Bold Italic
  • Adjustable font sizes as percentage of poster height
  • Hex color customization for all text elements
  • Background overlay colors with alpha transparency
  • Image fill strategies: Original, Fill, Fit