---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.22"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  features:
  - Allow for Extract Window configuration
  - Allow for custom Graphics on top of the overlay
  - Allow clearing the database of previously processed work
  fixes: 
  - Fix missing Plugin Page
  - Only track changes to poster configurations not task/provider changes
  technical:
  - Rework to a generic 4 layer structure for extensibility
  - Use HWA filters instead of always defaulting to SW
  - VideoToolBox always defaults to SW tone mapping
  other:
  - Standardize all comments in code 
  documentation:
  - Update Read Me to better explain the processing
  - Renew screenshots on latest version
  - Add screenshot configuration steps
