---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.23"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  features:
  - Allow disabling HWA
  fixes: 
  - Disable HWA by default to prevent issues with VPP / VideoToolBox filters
  technical:
  - -
  other:
  - Will need to get HWA more stable in a later release
  documentation:
  - -
