---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.18"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  features:
  - Attempt at multi-threaded FFmpeg for black extractions
  fixes: 
  - Missing Logo
  technical:
  - -
  other:
  - -
  documentation:
  - Reduce comments and documentation
