---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.29"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  fixes: 
  - Fixed BT.2390 tone mapping failing with "Undefined constant" error
  - Fixed plugin logo not displaying in repository/installed plugins view
  technical:
  - Corrected tone mapping filter syntax from 'tonemap=tonemap={algorithm}' to 'tonemap={algorithm}' in ToneMapFilterService
  - Removed GetImage() method from Plugin.cs to use Jellyfin's default embedded resource mechanism