---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.6"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  features:
  - Run as Scheduled Task
  - Track processed Episodes for Scheduled Tasks
  - Choose to not extract an image if you want to just use colors
  - Allow Logo positioning
  - Allow episode images on all poster types if wanted
  - Allow skipping frame extraction for all poster types
  fixes: 
  - Prevent re-processing previously processed posters
  - Updating the poster design will make re-enable processing for posters that used the previous design
  technical:
  - Proper dependency injection
  - SQL DB for tracking episode changes - Should track manual poster updates as well.
  other:
  - -
  documentation:
  - Better, inline documentation and summaries