---
name: "Episode Poster Generator"
guid: "b8715e44-6b77-4c88-9c74-2b6f4c7b9a1e"
version: "10.10.4"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Generate Custom Episode Posters"
description: >
  Episode Poster Generator is a Jellyfin plugin that automatically creates custom episode posters using smart frame analysis, black frame detection, and configurable text styling. Perfect for filling in missing or generic episode artwork with clean, consistent visuals.
category: "Metadata"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.EpisodePosterGenerator.dll"
changelog:
  features:
  - Add new Logo poster
  - Add a safe area configuration for parameter padding
  fixes: 
  - Improve font handling to prevent overlapping
  - Improve Standard poster text placement
  - Improve Cutout poster text placement
  technical:
  - Better code documentation on posters
  - Better padding / safe area inheritance
  - Migrate all Text functionality into its own utility
  other:
  - Updated screenshots to show multiple variations of each poster type
  documentation:
  - New changelog formatting
  - Summarize all poster code for better readibility