# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: JPKribs/jellyfin-plugin-episodepostergenerator/.github/workflows/command-dispatch.yaml@master
    secrets:
      token: .
